volumes:
  postgres_data:
  static_data:
  media_data:

services:
  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

  backendapp:
    build: ./reseption
    env_file: .env
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    depends_on:
      - db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: sh -c 'python3 manage.py makemigrations &&
                    python3 manage.py migrate &&
                    python3 manage.py collectstatic --noinput &&
                    gunicorn reseption.wsgi:application --bind 0.0.0.0:8000 --workers 3 --access-logfile - --error-logfile -"
