# Generated by Django 5.2.2 on 2025-06-10 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Option Group Name')),
                ('option_type', models.CharField(choices=[('radio', 'Radio Button'), ('select', 'Dropdown')], default='radio', max_length=10, verbose_name='Option Type')),
            ],
            options={
                'verbose_name': 'Option Group',
                'verbose_name_plural': 'Option Groups',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Price')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('product_url', models.URLField(max_length=1024, unique=True, verbose_name='Product Page URL')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OptionVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Display Text (for select)')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Variant Image URL')),
                ('price_modifier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price Modifier')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.optiongroup', verbose_name='Option Group')),
            ],
            options={
                'verbose_name': 'Option Variant',
                'verbose_name_plural': 'Option Variants',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.product', verbose_name='Product'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1024, verbose_name='Image URL')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='optiongroup',
            unique_together={('product', 'name')},
        ),
    ]
