# Generated by Django 5.2.2 on 2025-06-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_optionvariant_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_images/%Y/%m/%d/', verbose_name='Variant Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_gallery/%Y/%m/%d/', verbose_name='Product Image'),
        ),
    ]
