# Generated by Django 5.2.2 on 2025-07-01 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_optionvariant_image_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionvariant',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
    ]
