# Generated by Django 5.2.2 on 2025-08-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_optionvariant_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
            ],
        ),
    ]
